### ISSUE TITLE
Players not really removed when disconnecting

### ISSUE THREAD

**Issue by dunklesToast** [NTA2017Racket/KotlinUniverse#1]
When a player joins and disconnects the game new Players wont get their place. They will just getting the next player number so when somebody disconnects from a full its not possible to join with another phone.

Bug or Feature?

**Comment by SpacialCircumstances** [comment]
No, that´s a bug. I thought that would happen rarely, as the matches only take 5 minutes. But I´ll fix it for the next release, it could be annoying.

**Comment by SpacialCircumstances** [comment]
Fixed by  [deb65adba01223e414dba60d0775fc7bf5ee2ae6](https://github.com/NTA2017Racket/KotlinUniverse/commit/deb65adba01223e414dba60d0775fc7bf5ee2ae6)
